site_name: DevOps journey
site_author: Mathod
site_url: https://mkdocs.mathod.fr/
repo_url: https://github.com/Mathod95/mkdocs
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Kubernetes:
    - kubernetes/index.md
    - Objets:
      - Namespace: kubernetes/objets/namespace/namespace.md
      - Pods:
        - Probes: kubernetes/objets/pods/probes/probes.md
        - Security Context: kubernetes/objets/pods/securityContext/securityContext.md
      - Deployment: kubernetes/objets/deployment/deployment.md
    - Tips: kubernetes/tips.md
    - Aliases: kubernetes/aliases.md
    - Generator: kubernetes/generator/test.md
    - Draft: kubernetes/draft.md
  - Clouds:
    - aws:
        - iam: clouds/aws/iam/iam.md
  - Crossplane: crossplane/index.md
  - Infra: infra/index.md
  - Apps:
    - Argo:
      - CD:
        - Autopilot: apps/argo/cd/autopilot/argo-cd-autopilot.md
      - Workflows: about/workflows.md
      - Events: about/Events.md
      - Rollouts: about/Rollouts.md
    - Cilium: about/cilium.md
    - Crossplane: 
      - apps/crossplane/index.md
      - Import: apps/crossplane/import.md
      - Providers:
        - ArgoCD: apps/crossplane/providers/argocd/crossplane_providers_argocd.md
    - Istio: about/istio.md
    - Kargo: about/kargo.md
    - Karpenter: about/karpenter.md
    - Keda: about/keda.md
    - KinD:
      - KinD: apps/kind/kind.md
      - Cheatsheet: apps/kind/cheatsheet.md
    - Kustomize: about/kustomize.md
    - Kube-score: about/kube-score.md
    - KubeBlocks: about/kubeblocks.md
    - Kyverno: apps/kyverno/kyverno.md
    - Prometheus: about/prometheus.md
    - Velero: about/velero.md
    - Helm:
        - Cheatsheet: apps/helm/cheatsheet.md
  - NixOS:
    - MyEnv: nixos/packages/packages.md
    - HomeManager: nixos/packages/home-manager.md
    - Hyprland: nixos/packages/hyprland.md
    - Packages:
      - Vim: nixos/packages/vim.md
  - Awesome: awesome.md
  - Glossaire: glosarry.md
  - Tags: tags.md
  - Blog:
    - blog/index.md
  - About:
    - About: about/index.md

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: blog
      post_dir: "{blog}/posts"
  - tags:
      enabled: true
  - toggle-sidebar: # https://github.com/six-two/mkdocs-toggle-sidebar-plugin
      show_navigation_by_default: True
      show_toc_by_default: True
      theme: material
      toggle_button: all
#  - glightbox: # https://github.com/blueswen/mkdocs-glightbox
#      touchNavigation: true
#      loop: false
#      effect: zoom
#      slide_effect: slide
#      width: 100%
#      height: auto
#      zoomable: true
#      draggable: true
#      skip_classes:
#        - custom-skip-class-name
#      auto_themed: false
#      auto_caption: false
#      caption_position: bottom
#      background: white
#      shadow: true
#      manual: false

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: red
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: teal
  features:
    # Setting up navigation
    - navigation.instant
#    - navigation.instant.prefetch # Sponsors only
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
#    - navigation.path # Sponsors only
    - navigation.indexes
    - toc.follow
    - navigation.top
    # Setting up site search
    - search.suggest
    - search.highlight
    - search.share
#    - content.action.edit
#    - content.action.view
    # Code blocks - https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    - content.code.copy
#    - content.code.select # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=copy+button#code-selection-button
    - content.code.annotate
    - content.tooltips
    - header.autohide
    - navigation.footer

# Python Markdown - https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      toc_depth: 6
      permalink: true
  - tables # Can be sort if configured
  - meta
  # Python Markdown Extensions - https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mathod95
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mathod/

watch:
  - includes